routes/web.php
<?php
Route::get('/', 'HomeController@index')->name('home');
Route::get('language/{lang}', 'HomeController@language');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
Route::post('login', 'Auth\LoginController@login')->name('auth.login');
Route::post('logout', 'Auth\LoginController@logout')->name('auth.logout');

Route::resource('drafts', 'DraftController');
Route::resource('comments', 'CommentController');
Route::get('pending','DraftController@approvals')->name('drafts.pending');
Route::get('archived','DraftController@archived')->name('drafts.archived');
Route::get('approvals/setread/{draft}/{id}','DraftController@setRead')->name('drafts.setread');
Route::post('drafts/approve','DraftController@approveDraft')->name('drafts.approve');
Route::post('drafts/reject','DraftController@rejectDraft')->name('drafts.reject');
Route::resource('doctypes', 'DocumentTypeController');

Route::get('/doctype/media/{doctype}','DocumentTypeController@media')->name('doctype.media');

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
Route::post('password/email'    , 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::get('/template/download/{mediaItem}','DocumentTypeController@download')->name('doctypes.download');
Route::get('/drafts/typedata/{type}','DraftController@typeData')->name('drafts.typedata');
Route::get('/drafts/media/{draft}','DraftController@media')->name('drafts.media');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::resource('department', 'Admin\DepartmentController');
    Route::resource('position', 'Admin\PositionController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
});

Route::get('/profile','ProfileController@profile')->name('profile');
Route::post('/profile/avatar','ProfileController@updateAvatar')->name('avatar.update');
Route::get('/profile/avatar','ProfileController@getAvatar')->name('avatar.get');
Route::get('/profile/avatar-thumb','ProfileController@getAvatarThumb')->name('avatar.thumb');
Route::get('/avatar-thumb/{user}','CommonController@getAvatarThumb')->name('common.avatar.thumb');

resources/views/doctypes/create.blade.php
@extends('layouts.admin')

@section('content')
    <h4 class="ui top attached header">
        <div>@lang('global.document_type')</div>
    </h4>
    {!! Form::open(['method' => 'POST','class'=>'ui form','enctype'=>'multipart/form-data', 'route' => ['doctypes.store']]) !!}
        <div id="approvers-block"></div>
        <div class="ui attached segment">
            <div class="two fields">
                <div class="field">
                    <label>@lang('global.name_uz')</label>
                    {!! Form::text('name_uz', old('name_uz'), ['placeholder' => '', 'required' => '']) !!}
                </div>
                <div class="field">
                    <label>@lang('global.name_ru')</label>
                    {!! Form::text('name_ru', old('name_ru'), ['placeholder' => '', 'required' => '']) !!}
                </div>
            </div>


                <div class="field">
                    <div class="ui checkbox">
                        {{ Form::checkbox('has_template', 1, false,['id'=>'has_template']) }}
                        <label>@lang('global.has_template')</label>
                    </div>
                </div>


            <div class="field">
                <div class="nine wide field" style="display: none;" id="file-block">
                    <input class="form-field" type="file" name="attachment" />
                </div>
            </div>
            <h5 class="ui dividing teal header">@lang('global.document_route')</h5>
            <div class="two fields">
                <div class="field">
                    <div class="ui checkbox">
                        <input type="checkbox" tabindex="0" class="hidden" name="chief_approval" id="chief-approval" value="1" />
                        <label>@lang('global.chief_approval')</label>
                    </div>
                </div>
                <div class="inline fields">
                    <label for="fruit">Вид:</label>
                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" name="seq" checked="" tabindex="0" class="hidden seq" value="SEQ" />
                            <label>Последовательное</label>
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" name="seq" tabindex="0" class="hidden seq" value="PAR" />
                            <label>Параллельное</label>
                        </div>
                    </div>
                </div>


            </div>
            <div class="ui ordered small computer stackable steps" id="steps">
            </div>
            <div class="field">
                <button type="button" class="ui small basic small button" id="add-point">@lang('global.add_approver')</button>
            </div>
        </div>
        <div class="ui bottom attached segment">
            {!! Form::submit(trans('global.app_save'), ['class' => 'ui positive button']) !!}
            <a href="{{route('doctypes.index')}}" class="ui button">Отмена</a>
      </div>
    {!! Form::close() !!}

    <!-- Modal -->
    <div class="ui small modal" id="routepoint-modal">
        <div class="header">@lang('global.add_approver')</div>
        <div class="content">
            <div class="ui form">
                <div class="field">
                    <select name="points" id="point-select">
                        <option value="">--Выберите согласующего--</option>
                        @foreach($users as $user)
                            <option value="{{$user->id}}"
                                    sname="{{$user->shortName()}}" job="{{$user->position->getName()}}">
                                {{$user->fullName()}}
                            </option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
        <div class="actions">
            <div class="ui approve green small button">@lang('global.app_save')</div>
            <div class="ui cancel small button">@lang('global.app_cancel')</div>
        </div>
    </div>
@stop

@section('javascript')
    <script src="{{ url('js/jquery.validate.min.js') }}"></script>
    <script src="{{ url('js/localization/messages_ru.min.js') }}"></script>
<script>

    $('form').validate();

    $(document).on('change','#chief-approval',function() {
        if($(this).is(':checked')) {
            var text='<div class="step" id="boss-step"><div class="content"><div class="title">Руководитель</div><div class="description">Согласовать с руководителем</div></div></div>';
            $('#steps').prepend(text);
        }else{
            $('#boss-step').remove();
        }
    });

    $(document).on('click','#add-point',function(){
        $('#point-select').val("");
        $('#routepoint-modal').modal({
            onApprove : function() {
                return savePoint(false);
            }
        }).modal('show');

    });

    function savePoint() {
        var selId=$('#point-select').val().trim();

        if(!selId) {
            return false;
        }

        var name=$('#point-select option:selected').attr('sname');
        var job=$('#point-select option:selected').attr('job');
        var text='<div class="step" user-id="'+selId+'"><div class="content"><div class="title">'+name+'<i class="circular times red small icon link remove-step"></i></div><div class="description">'+job+'</div></div></div>';
        if($('#performer-step').length>0) {
            $(text).insertBefore('#performer-step');
        }else{
            $('#steps').append(text);
        }
        $('#approvers-block').append('<input type="hidden" class="approver_input" name="approvers[]" value="'+selId+'" />');

        $('#point-select option[value='+selId+']').hide();
    }
    $(document).on('click','.remove-step',function(e) {
        var step=$(this).closest('.step');
        var uid = step.attr('user-id');
        step.remove();
        $('input.approver_input[value='+uid+']').remove();
        $('#point-select option[value='+uid+']').show();
    });
    $(document).on('change','#has_template',function() {
        if($(this).is(':checked')) {
            $('#file-block').show();
        }else{
            $('#file-block').hide();
        }
    });
    $(document).on('change','.seq',function (e) {
        var seq=$('input[name="seq"]:checked').val();
        $('#steps').removeClass('ordered');
        if(seq=='SEQ') $('#steps').addClass('ordered');
    })
</script>
@endsection

resources/views/doctypes/edit.blade.php
@extends('layouts.admin')

@section('content')
    <h4 class="ui top attached header">
        <div>@lang('global.document_type')</div>
    </h4>
    {!! Form::model($doctype,['method' => 'PUT','class'=>'ui form','enctype'=>'multipart/form-data', 'route' => ['doctypes.update',$doctype->id]]) !!}
        <div id="approvers-block">
            @if($doctype->approvers)
                @foreach($doctype->approvers as $approver)
                <input type="hidden" class="approver_input" name="approvers[]" value="{{$approver->id}}" />
                @endforeach
            @endif
        </div>
        <div class="ui attached segment">
            <div class="two fields">
                <div class="field">
                    <label>@lang('global.name_uz')</label>
                    {!! Form::text('name_uz', old('name_uz'), ['placeholder' => '', 'required' => '']) !!}
                </div>
                <div class="field">
                    <label>@lang('global.name_ru')</label>
                    {!! Form::text('name_ru', old('name_ru'), ['placeholder' => '', 'required' => '']) !!}
                </div>
            </div>


                <div class="field">
                    <div class="ui checkbox">
                        {{ Form::checkbox('has_template', 1, $doctype->has_template,['id'=>'has_template']) }}
                        {{--<input type="checkbox" tabindex="0" class="hidden" name="has_template" id="has_template" value="1" />--}}
                        <label>@lang('global.has_template')</label>
                    </div>
                </div>
                @if($doctype->has_template)
                    <div class="two fields file-block">
                        <div class="field">
                            <h4 class="ui image header">
                                <img src="/img/filetypes/{{ $doctype->getFirstMedia('templates')->extension}}.png" class="ui image">
                                <div class="content">
                                    <a href="/template/download/{{$doctype->getFirstMedia('templates')->id}}">{{ $doctype->getFirstMedia('templates')->file_name }}</a>
                                    <div class="sub header">{{ $doctype->getFirstMedia('templates')->human_readable_size }}</div>
                            </h4>
                        </div>
                        <div class="field">
                            <button type="button" class="ui button" id="change-attachment">Заменить</button>
                            <input class="form-field" type="file" name="attachment" id="attachment-field" style="display: none;" />
                        </div>
                    </div>
                @else
                    <div class="field file-block" {!! $doctype->has_template==0 ? 'style="display:none;"' : ''  !!} >
                        <input class="form-field" type="file" name="attachment" />
                    </div>

                @endif

            <h5 class="ui dividing teal header">@lang('global.document_route')</h5>
            <div class="two fields">
                <div class="field">
                    <div class="ui checkbox">
                        {{ Form::checkbox('chief_approval', 1, $doctype->chief_approval,['id'=>'chief-approval']) }}
                        {{--<input type="checkbox" tabindex="0" class="hidden" name="chief_approval" id="chief-approval" value="1" />--}}
                        <label>@lang('global.chief_approval')</label>
                    </div>
                </div>
                <div class="inline fields">
                    <label for="fruit">Вид:</label>
                    <div class="field">
                        <div class="ui radio checkbox">
                            {{ Form::radio('seq', 'SEQ', $doctype->seq=='SEQ',['class'=>'seq']) }}
                            {{--<input type="radio" name="seq" checked="" tabindex="0" class="hidden seq" value="SEQ" />--}}
                            <label>Последовательное</label>
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui radio checkbox">
                            {{ Form::radio('seq', 'PAR', $doctype->seq=='PAR',['class'=>'seq']) }}
                            {{--<input type="radio" name="seq" tabindex="0" class="hidden seq" value="PAR" />--}}
                            <label>Параллельное</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ui ordered small computer {{$doctype->seq=='SEQ' ? 'stackable' : ''}} steps" id="steps">
                @if($doctype->chief_approval)
                    <div class="step" id="boss-step">
                        <div class="content">
                            <div class="title">Руководитель</div>
                            <div class="description">Согласовать с руководителем</div>
                        </div>
                    </div>
                @endif
                @if($doctype->approvers())

                    @foreach($doctype->approvers as $approver)
                            <div class="step" user-id="{{$approver->id}}">
                                <div class="content">
                                    <div class="title">{{$approver->shortName()}}<i class="circular times red small icon link remove-step"></i></div>
                                    <div class="description">{{$approver->position->getName()}}</div>
                                </div>
                            </div>
                    @endforeach
                @endif
            </div>
            <div class="field">
                <button type="button" class="ui small basic small button" id="add-point">@lang('global.add_approver')</button>
            </div>
        </div>
        <div class="ui bottom attached segment">
            {!! Form::submit(trans('global.app_save'), ['class' => 'ui positive button']) !!}
            <a href="{{route('doctypes.index')}}" class="ui button">Отмена</a>
      </div>
    {!! Form::close() !!}

    <!-- Modal -->
    <div class="ui small modal" id="routepoint-modal">
        <div class="header">@lang('global.add_approver')</div>
        <div class="content">
            <div class="ui form">
                <div class="field">
                    <select name="points" id="point-select">
                        <option value="">--Выберите согласующего--</option>
                        @foreach($users as $user)
                            <option value="{{$user->id}}"
                                    sname="{{$user->shortName()}}" job="{{$user->position->getName()}}">
                                {{$user->fullName()}}
                            </option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
        <div class="actions">
            <div class="ui approve green small button">@lang('global.app_save')</div>
            <div class="ui cancel small button">@lang('global.app_cancel')</div>
        </div>
    </div>
@stop

@section('javascript')
    <script src="{{ url('js/jquery.validate.min.js') }}"></script>
    <script src="{{ url('js/localization/messages_ru.min.js') }}"></script>
<script>

    $('form').validate();

    $(document).on('change','#chief-approval',function() {
        if($(this).is(':checked')) {
            var text='<div class="step" id="boss-step"><div class="content"><div class="title">Руководитель</div><div class="description">Согласовать с руководителем</div></div></div>';
            $('#steps').prepend(text);
        }else{
            $('#boss-step').remove();
        }
    });

    $(document).on('click','#add-point',function(){
        $('#point-select').val("");
        $('#routepoint-modal').modal({
            onApprove : function() {
                return savePoint(false);
            }
        }).modal('show');

    });

    function savePoint() {
        var selId=$('#point-select').val().trim();

        if(!selId) {
            return false;
        }

        var name=$('#point-select option:selected').attr('sname');
        var job=$('#point-select option:selected').attr('job');
        var text='<div class="step" user-id="'+selId+'"><div class="content"><div class="title">'+name+'<i class="circular times red small icon link remove-step"></i></div><div class="description">'+job+'</div></div></div>';
        if($('#performer-step').length>0) {
            $(text).insertBefore('#performer-step');
        }else{
            $('#steps').append(text);
        }
        $('#approvers-block').append('<input type="hidden" class="approver_input" name="approvers[]" value="'+selId+'" />');

        $('#point-select option[value='+selId+']').hide();
    }
    $(document).on('click','.remove-step',function(e) {
        var step=$(this).closest('.step');
        var uid = step.attr('user-id');
        step.remove();
        $('input.approver_input[value='+uid+']').remove();
        $('#point-select option[value='+uid+']').show();
    });
    $(document).on('change','#has_template',function() {
        if($(this).is(':checked')) {
            $('.file-block').show();
        }else{
            $('.file-block').hide();
        }
    });
    $(document).on('change','.seq',function (e) {
        var seq=$('input[name="seq"]:checked').val();
        $('#steps').removeClass('ordered');
        if(seq=='SEQ') $('#steps').addClass('ordered');
    });
    $(document).on('click','#change-attachment',function () {
       $('#attachment-field').show();
       $(this).hide();
    });
</script>
@endsection

resources/views/doctypes/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.admin')

@section('content')
    <h5 class="ui top attached header">
        @lang('global.document_types')
    </h5>
    <div class="ui attached segment">
        <a href="{{ route('doctypes.create') }}" class="ui mini vk button">@lang('global.app_add_new')</a>
        <table class="ui table table-striped {{ count($list) > 0 ? 'datatable' : '' }} dt-select">
            <thead>
            <tr>
                {{--<th style="text-align:center;"><input type="checkbox" id="select-all" /></th>--}}
                <th></th>
                <th>@lang('global.name_uz')</th>
                <th>@lang('global.name_ru')</th>
                <th>@lang('global.signer_list')</th>
                <th>&nbsp;</th>
            </tr>
            </thead>

            <tbody>
            @if (count($list) > 0)
                @foreach ($list as $item)
                    <tr data-entry-id="{{ $item->id }}">
                        <td>
                            @if($item->has_template)
                                <i class="file alternate outline icon"></i>
                                @endif
                        </td>
                        <td>{{ $item->name_uz }}</td>
                        <td>{{ $item->name_ru }}</td>
                        <td>
                            <ul>
                            @if($item->chief_approval)
                                <li>Руководитель</li>
                            @endif
                            @foreach($item->approvers as $approver)
                            <li>{{ $approver->shortName() }}</li>
                                @endforeach
                            </ul>
                        </td>
                        <td>
                            <a href="{{ route('doctypes.edit',[$item->id]) }}" class="ui mini facebook button">@lang('global.app_edit')</a>
                            {!! Form::open(array(
                                'style' => 'display: inline-block;',
                                'method' => 'DELETE',
                                'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                'route' => ['doctypes.destroy', $item->id])) !!}
                            {!! Form::submit(trans('global.app_delete'), array('class' => 'ui mini red button')) !!}
                            {!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
            @else
                <tr>
                    <td colspan="4">@lang('global.app_no_entries_in_table')</td>
                </tr>
            @endif
            </tbody>
        </table>

    </div>


@stop

@section('javascript')
    <script>

    </script>
@endsection