routes/web.php
<?php
Route::get('/', 'HomeController@index')->name('home');
Route::get('language/{lang}', 'HomeController@language');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
Route::post('login', 'Auth\LoginController@login')->name('auth.login');
Route::post('logout', 'Auth\LoginController@logout')->name('auth.logout');

Route::resource('drafts', 'DraftController');
Route::resource('comments', 'CommentController');
Route::get('pending','DraftController@approvals')->name('drafts.pending');
Route::get('archived','DraftController@archived')->name('drafts.archived');
Route::get('approvals/setread/{draft}/{id}','DraftController@setRead')->name('drafts.setread');
Route::post('drafts/approve','DraftController@approveDraft')->name('drafts.approve');
Route::post('drafts/reject','DraftController@rejectDraft')->name('drafts.reject');
Route::resource('doctypes', 'DocumentTypeController');

Route::get('/doctype/media/{doctype}','DocumentTypeController@media')->name('doctype.media');

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
Route::post('password/email'    , 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::get('/template/download/{mediaItem}','DocumentTypeController@download')->name('doctypes.download');
Route::get('/drafts/typedata/{type}','DraftController@typeData')->name('drafts.typedata');
Route::get('/drafts/media/{draft}','DraftController@media')->name('drafts.media');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::resource('department', 'Admin\DepartmentController');
    Route::resource('position', 'Admin\PositionController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
});

Route::get('/profile','ProfileController@profile')->name('profile');
Route::post('/profile/avatar','ProfileController@updateAvatar')->name('avatar.update');
Route::get('/profile/avatar','ProfileController@getAvatar')->name('avatar.get');
Route::get('/profile/avatar-thumb','ProfileController@getAvatarThumb')->name('avatar.thumb');
Route::get('/avatar-thumb/{user}','CommonController@getAvatarThumb')->name('common.avatar.thumb');

app/Draft.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Lang;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Carbon;

class Draft extends Model implements HasMedia
{
    use HasMediaTrait;

    protected $fillable=['user_id','subject','document_type_id','status'];
    protected $searchable = ['name'];

    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $model->user_id = Auth::id();
        });
    }
    public function registerMediaCollections()
    {
        $this->addMediaCollection('attachment')
            ->singleFile();
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function type()
    {
        return $this->belongsTo(DocumentType::class,'document_type_id');
    }
    public function approvers()
    {
        return $this->belongsToMany(User::class,'draft_approvers')
            ->withPivot('status','read_at','approved_at')->withTimestamps();
    }
    public function queuedApprovers()
    {
        return $this->belongsToMany(User::class,'draft_approvers')->wherePivot('status','QUEUED');
    }
    public function isAllApproved()
    {
        $approvedCount=$this->approvers()->wherePivot('status','APPROVED')->count();
        $total=$this->approvers()->count();
        return $approvedCount==$total;
    }
    public function comments()
    {
        return $this->hasMany(Comment::class)->whereNull('parent_id');
    }
    public function allComments()
    {
        return $this->hasMany(Comment::class);
    }
    public function getRegDateAttribute() {
        return Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $this->created_at)->format('d.m.Y H:i');
    }
    public function statusname()
    {
        $states=Lang::get('global.statusname');
        return $states[$this->status];
    }
    public function approverStatus($status,$with_label=true)
    {
        $states=Lang::get('global.approver_states');
        if($with_label) {
            $labelColor='';
            switch ($status)
            {
                case 'PENDING':
                    $labelColor='orange';
                    break;
                case 'APPROVED':
                    $labelColor='green';
                    break;
                case 'RETURNED':
                    $labelColor='red';
                    break;
                default:
                    $labelColor='';
            }
            $ret='<span class="ui '.$labelColor.' label">'.$states[$status].'</span>';
        }else{
            $ret=$states[$status];
        }
        return $ret;
    }
    public function getStatusClass() {

        switch ($this->status) {
            case 'PENDING':
                $class="ui teal label";
                break;
            case 'APPROVED':
                $class="ui green label";
                break;
            case 'REJECTED':
                $class="ui red label";
                break;
            default:
                $class="ui label";
                break;
        }
        return $class;
    }
}

app/Http/Controllers/DraftController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\DocumentType;
use App\Draft;
use App\Http\Requests\StoreDraftRequest;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class DraftController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //Created by me
        $list=Auth::user()->drafts()->withCount('allComments')->with('approvers')->latest()->paginate(15);
        return view('drafts.index',compact('list'));
    }
    public function approvals()
    {
        $list=Auth::user()->pendingApprovals()->with('approvers')->withCount('allComments')->latest()->paginate(15);
        return view('drafts.index',compact('list'));
    }
    public function archived()
    {
        $list=Auth::user()->archivedApprovals()->with('approvers')->withCount('allComments')->latest()->paginate(15);
        return view('drafts.index',compact('list'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $types = DocumentType::get()->pluck('name_ru', 'id');
        $types->prepend('--Не выбран--','');
        return view('drafts.create',compact('types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreDraftRequest $request)
    {
        $doc=Draft::create($request->all());
        //Save attachment
        if($request->hasFile('attachment')) {
            $doc->addMediaFromRequest('attachment')->toMediaCollection('attachment');
        }
        //Approvers
        $approvers=[];
        $dt=DocumentType::find($doc->document_type_id);
        if($dt) {
            if($dt->chief_approval) {
                $boss=Auth::user()->getBoss();
                if($boss) {
                    $approvers[]=$boss->id;
                }
            }
            $apprs=$dt->approvers;
            if($apprs) {
                foreach ($apprs as $appr) {
                    $approvers[]=$appr->id;
                }
            }
            if(count($approvers)>0) {
                $doc->approvers()->attach($approvers);
                if($dt->seq=='SEQ') {
                    //sequental
                    $doc->approvers()->update(['status'=>'QUEUED']);
                    $doc->approvers()->first()->pivot->update(['status'=>'PENDING']);
                }
            }
        }
        return redirect(route('drafts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Draft  $draft
     * @return \Illuminate\Http\Response
     */
    public function show(Draft $draft)
    {
        return view('drafts.view',compact('draft'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Draft  $draft
     * @return \Illuminate\Http\Response
     */
    public function edit(Draft $draft)
    {
        $types = DocumentType::get()->pluck('name_ru', 'id');
        return view('drafts.edit',compact('draft','types'));
    }

    public function setRead(Draft $draft,$id)
    {
        $draft->approvers->find($id)->pivot->update(['read_at'=>\Carbon\Carbon::now()]);
        $result=array('result'=>'success');
        return response()->json($result);
    }
   /* public function approveDraft(Draft $draft,$id)
    {
        $draft->approvers->find($id)->pivot->update(['status'=>'APPROVED','approved_at'=>\Carbon\Carbon::now()]);
        $result=array('result'=>'success');
        return response()->json($result);
    }*/
    public function approveDraft(Request $request)
    {
        $draft=Draft::find($request['draft']);
        $appId=$request['approver'];
        $draft->approvers->find($appId)->pivot->update(['status'=>'APPROVED','approved_at'=>\Carbon\Carbon::now()]);
        if($draft->type->seq=='SEQ') {
            //Pass to next approver
            $draft->queuedApprovers()->first()->pivot->update(['status'=>'PENDING']);
        }
        if($draft->isAllApproved()) {
            //Set draft approved
            $draft->status='APPROVED';
            $draft->save();
        }
        return redirect('/drafts/'.$draft->id);
    }
    public function rejectDraft(Request $request)
    {
        $draft=Draft::find($request['draft']);
        $appId=$request['approver'];
        $draft->approvers->find($appId)->pivot->update(['status'=>'RETURNED']);

        $comment=new Comment();
        $comment->draft_id=$draft->id;
        $comment->user_id=Auth::user()->id;
        $comment->body=$request['comment'];
        $comment->save();

        return redirect('/drafts/'.$draft->id);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Draft  $draft
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $this->validate(request(),[
            'subject' =>'required',
        ]);
        $draft=Draft::find($request["id"]);
        $draft->subject=$request["subject"];

        //Save attachment
        if($request->hasFile('attachment')) {
            $draft->addMediaFromRequest('attachment')->toMediaCollection('attachment');
            $draft->increment('version');
            //Set approvers status when file changed
            $draft->approvers()->update(['read_at'=>null,'approved_at'=>null]);
            if($draft->type->seq=='SEQ') {
                //sequental
                $draft->approvers()->update(['status'=>'QUEUED']);
                $draft->approvers()->first()->pivot->update(['status'=>'PENDING']);
            }else{
                //parallel
                $draft->approvers()->update(['status'=>'PENDING']);
            }
        }
        $draft->save();
        return redirect(route('drafts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Draft  $draft
     * @return \Illuminate\Http\Response
     */
    public function destroy(Draft $draft)
    {
        $draft->delete();
        return redirect(route('drafts.index'));
    }

    public function typeData(DocumentType $type)
    {
        $me=Auth::user();
        $users=$type->approvers()->get();
        $approvers=array();
        if($type->chief_approval) {
            $boss=$me->getBoss();
            if($boss) {
                $approvers[]=['id'=>$boss->id,'name'=>$boss->shortName(),'post'=>$boss->position->getName()];
            }
        }

        foreach ($users as $user) {
            $approvers[]=['id'=>$user->id,'seq'=>$type->seq,'name'=>$user->shortName(),'post'=>$user->position->getName()];
        }
        $chiefApr=$type->chief_approval;
        $hasTmplate=$type->has_template;
//        $fileUrl=$type->getFirstMediaUrl('templates');

        $fileUrl=$hasTmplate ? route('doctype.media',$type->id) : '';

        $result=array('result'=>'success','approvers'=>$approvers,'cheif'=>$chiefApr,'hastmp'=>$hasTmplate,'url'=>$fileUrl);
        return response()->json($result);
    }
    public function media(Draft $draft)
    {
        $mediaItem=$draft->getFirstMedia('attachment');
        return response()->download($mediaItem->getPath(), $mediaItem->file_name);
    }
}

resources/views/drafts/approvals.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content area -->
    @if (count($list)== 0)
        <div class="ui placeholder segment">
            <div class="ui icon header">
                <i class="folder open outline icon"></i>
                Нет записей
            </div>

            <a href="{{route('drafts.create')}}" class="ui primary button">Добавить документ</a>
        </div>
   @else
   <div class="ui segment">
        <table class="ui very basic small table">
            <tbody>
            @foreach($list as $item)
                <tr item-id="{{$item->id}}">
                    <td class="name">
                        <h4 class="ui image header">
                            <img src="/img/filetypes/{{$item->getFirstMedia('attachment')->extension}}.png" class="ui image">
                            <div class="content">
                                <a href="/template/download/{{$item->getFirstMedia('attachment')->id}}">{{$item->subject}}"</a>
                                <div class="sub header">{{$item->reg_date}}, автор: {{$item->user->shortName()}}, {{$item->getFirstMedia('attachment')->human_readable_size}}</div>
                            </div>
                        </h4>
                    </td>
                    <td>
                        <a class="ui basic orange small label">На согласовании</a>
                    </td>
                    <td class="right aligned">
                        <div class="ui right pointing dropdown icon button" tabindex="0">
                            <i class="ellipsis vertical icon"></i>
                            <div class="menu left transition hidden" tabindex="-1">
                                <div class="item edit-doc"><i class="edit icon"></i> Просмотр</div>
                                <div class="item del-item"><i class="delete icon"></i> Утвердить</div>
                            </div>
                        </div>
                    </td>
                </tr>
            @endforeach

                {{--    <tr item-id="98">
                        <td class="name">		   		<h4 class="ui image header">
                                <img src="{{asset('img/filetypes1/docx.png')}}" class="ui image">
                                <div class="content"><a id="98" class="file_lnk " ext="docx" href="openfile.php?aku=ZmlsZW5hbWU9ZG9jdW1lbnRzL3Byb2plY3QvOTguZG9jeA==">20.06. ИНФОРМАЦИЯ  по объет   .docx</a>	               <div class="sub header">Загружено 21.06.2018 09:49, автор: 42Kb	               </div>
                                </div></h4>

                        </td>
                        <td>
                            <a class="ui basic orange label">На согласовании</a>
                        </td>
                        <td class="right aligned"><button class="ui icon button del-item"><i class="trash icon"></i></button></td>
                    </tr>
                 --}}
                  </tbody>
                </table>
                </div>
    @endif
@endsection

resources/views/drafts/index.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content area -->
    @if (count($list)== 0)
        <div class="ui placeholder segment">
            <div class="ui icon header">
                <i class="folder open outline icon"></i>
                Нет записей
            </div>

            <a href="{{route('drafts.create')}}" class="ui primary button">Добавить документ</a>
        </div>
   @else
   <div class="ui segment">
        <table class="ui very basic small table">
            <thead>
            <tr>
                <th>Детали</th>
                <th>Согласующие</th>
                <th>Комментарии</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            @foreach($list as $item)
                <tr item-id="{{$item->id}}">
                    <td class="name">
                        <h4 class="ui image header">
                            <img src="/img/filetypes/{{$item->getFirstMedia('attachment')->extension}}.png" class="ui image">
                            <div class="content">
                                <a href="{{route('drafts.show',$item->id)}}">{{$item->subject}}</a>
                                <div class="sub header">{{$item->regDate}}, автор: {{$item->user->shortName()}}, Версия: {{$item->version}}</div>
                                <div class="sub header"> <a href="/template/download/{{$item->getFirstMedia('attachment')->id}}">{{$item->getFirstMedia('attachment')->name}}, {{$item->getFirstMedia('attachment')->human_readable_size}}</a></div>
                            </div>
                        </h4>
                    </td>
                    <td>
                        <div class="ui selection list">
                            @foreach($item->approvers as $approver)
                                <a class="item">
                                    <i class="help icon"></i>
                                    <div class="content">
                                    {{--<div class="ui orange horizontal small basic label">На ожидании</div>--}}
                                    {{ $approver->shortName() }}
                                    </div>
                                </a >
                            @endforeach
                        </div>
                        {{--<a class="ui basic orange small label">На согласовании</a>--}}
                    </td>
                    <td>
                        <button class="ui mini button comment-link">{{$item->all_comments_count}}
                            {{--<div class="floating ui red tiny label">5</div>--}}
                        </button>
                    </td>
                    <td class="right aligned">
                        @can('edit',$item)
                        <a href="{{ route('drafts.edit',[$item->id]) }}" class="ui mini icon button" data-tooltip="@lang('global.app_edit')" ><i class="edit icon"></i></a>
                        @endcan
                        @can('delete',$item)
                        {!! Form::open(array(
                            'style' => 'display: inline-block;',
                            'method' => 'DELETE',
                            'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                            'route' => ['drafts.destroy', $item->id])) !!}
                        {{--{!! Form::submit(trans('global.app_delete'), array('class' => 'ui mini red button')) !!}--}}
                        <button type="submit" class="ui mini red icon button" data-tooltip="@lang('global.app_delete')"><i class="trash alternate icon"></i></button>
                        {!! Form::close() !!}
                        @endcan
                            <a class="ui mini button" role="button" href="{{route('drafts.show',$item->id)}}">Детали</a>
                       {{-- <div class="ui right pointing dropdown icon button" tabindex="0">
                            <i class="ellipsis vertical icon"></i>
                            <div class="menu left transition hidden" tabindex="-1">
                                <div class="item edit-doc"><i class="edit icon"></i> Просмотр</div>
                                <div class="item del-item"><i class="delete icon"></i> Удалить</div>
                            </div>
                        </div>--}}
                    </td>
                </tr>
            @endforeach

                {{--    <tr item-id="98">
                        <td class="name">		   		<h4 class="ui image header">
                                <img src="{{asset('img/filetypes1/docx.png')}}" class="ui image">
                                <div class="content"><a id="98" class="file_lnk " ext="docx" href="openfile.php?aku=ZmlsZW5hbWU9ZG9jdW1lbnRzL3Byb2plY3QvOTguZG9jeA==">20.06. ИНФОРМАЦИЯ  по объет   .docx</a>	               <div class="sub header">Загружено 21.06.2018 09:49, автор: 42Kb	               </div>
                                </div></h4>

                        </td>
                        <td>
                            <a class="ui basic orange label">На согласовании</a>
                        </td>
                        <td class="right aligned"><button class="ui icon button del-item"><i class="trash icon"></i></button></td>
                    </tr>
                 --}}
                  </tbody>
                </table>
                </div>
    @endif
@endsection

resources/views/drafts/view.blade.php
@extends('layouts.app')
@section('content')
    <!-- Content area -->
    <div class="ui container">
        <div class="ui top attached secondary segment">
            <h4>@lang('global.app_view')</h4>
        </div>
        <div class="ui attached segment">
            <div class="ui items">
                <div class="item">
                    <div class="ui tiny image">
                        <img  src="{{route('common.avatar.thumb',$draft->user->id)}}" />
                    </div>
                    <div class="content">
                        <a class="header">{{$draft->subject}}</a>
                        <div class="meta">
                            <span class="cinema">{{$draft->regDate}}, {{$draft->user->shortName()}}, Версия: {{$draft->version}} </span>
                        </div>
                        <div class="description">
                            <p>Тип: {{$draft->type->getName()}}</p>
                        </div>
                        <div class="extra">
                            <a class="ui label" href="{{route('drafts.media',$draft->id)}}"><i class="file alternate icon"></i> {{$draft->getFirstMedia('attachment')->file_name}}</a>
                            <div class="{{$draft->getStatusClass()}}">{{$draft->statusname()}}</div>
                            <a href="{{route('drafts.edit',$draft->id)}}" class="ui label">Изменить</a>
                        </div>
                    </div>
                </div>
            </div>


           <h4>Маршрут согласования</h4>
            <table class="ui small table">
                <thead>
                <tr>
                    <th>@lang('global.approver_name')</th>
                    <th>@lang('global.read_at')</th>
                    <th>@lang('global.status')</th>
                    <th>@lang('global.approved_at')</th>
                    <th>@lang('global.actions')</th>
                </tr>
                </thead>
                @foreach($draft->approvers as $approver)
                    <tr item-id="{{$approver->id}}">
                        <td>{{$approver->shortName()}}</td>
                        <td>{{$approver->pivot->read_at}}</td>
                        <td>{!! $draft->approverStatus($approver->pivot->status)  !!}</td>
                        <td>{{$approver->pivot->approved_at}}</td>
                        <td>
                            @if($approver->pivot->status=='PENDING' && $approver->id==Auth::user()->id)
                                @if($approver->pivot->read_at==null)
                                    <input type="hidden" id="make-read" value="{{$approver->id}}" />
                                @endif
                                {!! Form::open(['method' => 'POST','id'=>'approve-form', 'route' => ['drafts.approve']]) !!}
                                    <input type="hidden" name="draft" value="{{$draft->id}}" />
                                    <input type="hidden" name="approver" value="{{$approver->id}}" />
                                    <button type="submit" class="ui left attached icon green small button approver" data-tooltip="Утвердить"><i class="thumbs up icon"></i></button>
                                    <button type="button" class="ui right attached icon orange small button rejector" data-tooltip="Отвергнуть с комментарием"><i class="thumbs down icon"></i></button>
                                 {!! Form::close() !!}
                                {{--rejector modal--}}
                                    <div class="ui small modal" id="reject-comment-modal">
                                        <div class="header">Комментарий</div>
                                        <div class="content">
                                            {!! Form::open(['method' => 'POST','class'=>'ui form validate','id'=>'reject-form', 'route' => ['drafts.reject']]) !!}
                                            <input type="hidden" name="draft" value="{{$draft->id}}" />
                                            <input type="hidden" name="approver" value="{{$approver->id}}" />
                                            <div class="field">
                                                <textarea name="comment" required="required"></textarea>
                                            </div>
                                            {!! Form::close() !!}
                                        </div>
                                        <div class="actions">
                                            <button type="button" id="reject-draft" class="ui green button">@lang('global.app_save')</button>
                                            <div class="ui negative button">@lang('global.app_cancel')</div>
                                        </div>

                                    </div>
                            @endif
                        </td>
                    </tr>
                    @endforeach
            </table>
            <h3 class="ui dividing header">Комментарии</h3>
            <div class="ui comments">
            @include('drafts.commentsDisplay', ['comments' => $draft->comments])
            </div>
            <button class="ui blue labeled icon small button" id="add-comment">
                <i class="icon edit"></i> Добавить комментарий
            </button>
            <a href="{{\Illuminate\Support\Facades\URL::previous()}}" class="ui button">Назад</a>

        </div>
    </div>
{{--comment modal--}}
    <div class="ui modal" id="comment-modal">
        <div class="header">Комментарий</div>
        <div class="content">
            <form class="ui form validate" id="comment-form" method="post" action="{{route('comments.store')}}">
                @csrf
                <input type="hidden" name="draft_id" value="{{ $draft->id }}" />
                <input type="hidden" name="parent_id" id="parent-id" />
                <div class="field">
                    <label>Текст комментария</label>
                    <textarea name="body" id="comment-body" required="required"></textarea>
                </div>
            </form>
        </div>
        <div class="actions">
            <div class="ui approve button">Сохранить</div>
            <div class="ui cancel button">Отмена</div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript" src="{{url('/js/jquery.validate.min.js')}}"></script>
    <script type="text/javascript" src="{{url('/js/localization/messages_ru.min.js')}}"></script>
    <script>
        var did={{$draft->id}};

        $(document).ready(function () {
            $('.validate').validate();
           if($('#make-read').length==1) {
               let id=$('#make-read').val();
               setWaitState(true);
               $.ajax({
                   type: 'get',
                   url: '/approvals/setread/'+did+'/'+id,
                   success: function(res){
                       if(res.result=='success')
                       {

                       }else{
                           alert(res.message);
                       }
                   },
                   error: function(data){
                       var errors = data.responseJSON;
                       console.log(errors.errors);
                       return false;
                       // Render the errors with js ...
                   },
                   complete: function() {
                       setWaitState(false);
                   }
               });
           }
        });

        $(document).on('click','.rejector',function () {
           $('#reject-comment-modal').modal('show');
        });
        $(document).on('click','#reject-draft',function () {
            $('#reject-form').submit();
        });

        $(document).on('click','#add-comment',function () {
           $('#comment-body').val('');
           $('#parent-id').val('');
           showCommentModal();
        });
// reply
        $(document).on('click','.reply',function (e) {
            e.preventDefault();
            var pid=$(this).attr('item-id');
            $('#comment-body').val('');
            $('#parent-id').val(pid);
            showCommentModal();
        });

        function showCommentModal() {
            $('#comment-modal').modal({
                onApprove: function () {
                    return saveComment();
                }
            }).modal('show');
        }

        function saveComment() {
            if($('#comment-form').valid()) {
                $('#comment-form').submit();
                return true;
            }else{
                return false;
            }
        }
    </script>
    @endsection