routes/web.php
<?php
Route::get('/', 'HomeController@index')->name('home');
Route::get('language/{lang}', 'HomeController@language');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
Route::post('login', 'Auth\LoginController@login')->name('auth.login');
Route::post('logout', 'Auth\LoginController@logout')->name('auth.logout');

Route::resource('drafts', 'DraftController');
Route::resource('comments', 'CommentController');
Route::get('pending','DraftController@approvals')->name('drafts.pending');
Route::get('archived','DraftController@archived')->name('drafts.archived');
Route::get('approvals/setread/{draft}/{id}','DraftController@setRead')->name('drafts.setread');
Route::post('drafts/approve','DraftController@approveDraft')->name('drafts.approve');
Route::post('drafts/reject','DraftController@rejectDraft')->name('drafts.reject');
Route::resource('doctypes', 'DocumentTypeController');

Route::get('/doctype/media/{doctype}','DocumentTypeController@media')->name('doctype.media');

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
Route::post('password/email'    , 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::get('/template/download/{mediaItem}','DocumentTypeController@download')->name('doctypes.download');
Route::get('/drafts/typedata/{type}','DraftController@typeData')->name('drafts.typedata');
Route::get('/drafts/media/{draft}','DraftController@media')->name('drafts.media');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::resource('department', 'Admin\DepartmentController');
    Route::resource('position', 'Admin\PositionController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
});

Route::get('/profile','ProfileController@profile')->name('profile');
Route::post('/profile/avatar','ProfileController@updateAvatar')->name('avatar.update');
Route::get('/profile/avatar','ProfileController@getAvatar')->name('avatar.get');
Route::get('/profile/avatar-thumb','ProfileController@getAvatarThumb')->name('avatar.thumb');
Route::get('/avatar-thumb/{user}','CommonController@getAvatarThumb')->name('common.avatar.thumb');

app/Position.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Position extends Model
{
    protected $fillable=['name_uz','name_ru'];
    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function getName()
    {
        $locale=\App::getLocale();
        return $locale=='ru' ? $this->name_ru : $this->name_uz;
    }
}

app/Http/Controllers/Admin/PositionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Position;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PositionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $list=Position::all();
        return view('admin.positions.index',compact('list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.positions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Position::create($request->all());
        return redirect()->route('admin.position.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function show(Position $position)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function edit(Position $position)
    {
        return view('admin.positions.edit',compact('position'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Position $position)
    {
        $position->update($request->all());
        return redirect()->route('admin.position.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function destroy(Position $position)
    {
        //
    }
}

resources/views/admin/positions/create.blade.php
@extends('layouts.admin')

@section('content')
    <h3 class="ui top attached segment">@lang('global.position')</h3>
    <div class="ui attached segment">
    {!! Form::open(['method' => 'POST','id'=>'inp-form','class'=>'ui form', 'route' => ['admin.position.store']]) !!}

            <div class="field">
                <label>@lang('global.name_uz')</label>
                {!! Form::text('name_uz', old('name_uz'), ['placeholder' => '', 'required' => 'required']) !!}
            </div>
            <div class="field">
                <label>@lang('global.name_ru')</label>
                {!! Form::text('name_ru', old('name_ru'), ['placeholder' => '', 'required' => 'required']) !!}
            </div>

        @include('partials.formerrors')
    {!! Form::submit(trans('global.app_save'), ['class' => 'ui positive button']) !!}
    <a href="{{route('admin.department.index')}}" class="ui button">Отмена</a>
    {!! Form::close() !!}
    </div>
@stop

@section('javascript')
    <script src="{{ url('js/jquery.validate.min.js') }}"></script>
    <script src="{{ url('js/localization/messages_ru.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#inp-form').validate();

        });

    </script>
@endsection

resources/views/admin/positions/edit.blade.php
@extends('layouts.admin')

@section('content')
    <h3 class="ui top attached segment">@lang('global.position')</h3>
    <div class="ui attached segment">
        {!! Form::model($position,['method' => 'PUT','id'=>'inp-form','class'=>'ui form', 'route' => ['admin.position.update',$position->id]]) !!}
        <div class="field">
                <label>@lang('global.name_uz')</label>
                {!! Form::text('name_uz', old('name_uz'), ['placeholder' => '', 'required' => 'required']) !!}
            </div>
            <div class="field">
                <label>@lang('global.name_ru')</label>
                {!! Form::text('name_ru', old('name_ru'), ['placeholder' => '', 'required' => 'required']) !!}
            </div>

        @include('partials.formerrors')
    {!! Form::submit(trans('global.app_save'), ['class' => 'ui positive button']) !!}
    <a href="{{route('admin.department.index')}}" class="ui button">Отмена</a>
    {!! Form::close() !!}
    </div>
@stop

@section('javascript')
    <script src="{{ url('js/jquery.validate.min.js') }}"></script>
    <script src="{{ url('js/localization/messages_ru.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#inp-form').validate();

        });

    </script>
@endsection

resources/views/admin/positions/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.admin')

@section('content')
    <h5 class="ui top attached header">
        @lang('global.positions')
    </h5>
    <div class="ui attached segment">
        <a href="{{ route('admin.position.create') }}" class="ui mini vk button">@lang('global.app_add_new')</a>
        <table class="ui celled table table-bordered table-striped {{ count($list) > 0 ? 'datatable' : '' }} dt-select">
            <thead>
            <tr>
                {{--<th style="text-align:center;"><input type="checkbox" id="select-all" /></th>--}}
                <th>@lang('global.name_uz')</th>
                <th>@lang('global.name_ru')</th>
                <th>@lang('global.count')</th>
                <th>&nbsp;</th>
            </tr>
            </thead>

            <tbody>
            @if (count($list) > 0)
                @foreach ($list as $item)
                    <tr data-entry-id="{{ $item->id }}">
                        <td>{{ $item->name_uz }}</td>
                        <td>{{ $item->name_ru}}</td>
                        <td>{{ $item->users()->count()}}</td>
                        <td>
                            <a href="{{ route('admin.position.edit',[$item->id]) }}" class="ui mini facebook button">@lang('global.app_edit')</a>
                            {!! Form::open(array(
                                'style' => 'display: inline-block;',
                                'method' => 'DELETE',
                                'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                'route' => ['admin.position.destroy', $item->id])) !!}
                            {!! Form::submit(trans('global.app_delete'), array('class' => 'ui mini red button')) !!}
                            {!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
            @else
                <tr>
                    <td colspan="4">@lang('global.app_no_entries_in_table')</td>
                </tr>
            @endif
            </tbody>
        </table>

    </div>
@stop

@section('javascript') 
    <script>

    </script>
@endsection